### ISSUE TITLE
v1 ... 1.5.0

### ISSUE THREAD

**Issue by godban** [zattoo/changelog#38]
I found weird to see v1 and then 1.5.0 without anything in middle, would be nice to create all releases we had before, even despite we used them under v1.

![image](https://user-images.githubusercontent.com/2461970/98100475-30a2d100-1e91-11eb-8f50-6a30997295ef.png)

**Comment by dobladov** [comment]
I made the tags and releases for previous versions.

The only thing to take into account is that shows `1.4.0` as **last release** instead of `1.5.0`, I think we have to delete 1.5.0 and recreate it to make it the last release. But I don't have permission. @godban let me know if we should delete and create this version again.

**Comment by godban** [comment]
@dobladov I wonder why you can't do this, you have admin permission for this repo.

Since we fully control usage, how about wipe it out one more time? And create `1.0.0` from recreated `v1` branch, what do you think?

**Comment by dobladov** [comment]
> I wonder why you can't do this, you have admin permission for this repo.
I managed to delete it, the button does not appear if you press edit, you have to press the title of the release to see it.

I also recreated 1.0.0

**Comment by godban** [comment]
Yes, it's a bit hidden, also you need remove release and tag separately, double-work

**Comment by godban** [comment]
let's leave only `1.0.0` under `v1` branch pointing to latest, changelog can be stripped too

**Comment by godban** [comment]
ok, I see you added all, let's keep like that, will do some minor tweaks
